[package]
name = "fleen-vm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Fleen virtual machine: verify and execute .fln source or .flnc bytecode"

[dependencies]
fleen-compiler = { path = "../fleen-compiler" }
fleen-verify = { path = "../fleen-verify" }
